const REACT_QUERY_KEYS = {
  GET_SEARCH_PRODUCTS: "GET_SEARCH_PRODUCTS",
  GET_SEARCH_INFINITE_PRODUCTS: "GET_SEARCH_INFINITE_PRODUCTS",
  GET_SEARCH_FILTERS: "GET_SEARCH_FILTERS",
  GET_SUGGESTED_SEARCH_TERMS: "GET_SUGGESTED_SEARCH_TERMS",
  GET_POPULAR_SEARCH_TERMS: "GET_POPULAR_SEARCH_TERMS",
};

export default REACT_QUERY_KEYS;
