const coutries = [
  { name: "Afghanistan", code: "AF" },
  { name: "Åland Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "AndorrA", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, The Democratic Republic of the", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cote D'Ivoire", code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Korea, Democratic People'S Republic of", code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Lao People'S Democratic Republic", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia and Montenegro", code: "CS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan, Province of China", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Virgin Islands, British", code: "VG" },
  { name: "Virgin Islands, U.S.", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

const vietnameCities = [
  {
    name: "An Giang",
    slug: "an-giang",
    type: "tinh",
    name_with_type: "Tỉnh An Giang",
    code: "89",
  },
  {
    name: "Kon Tum",
    slug: "kon-tum",
    type: "tinh",
    name_with_type: "Tỉnh Kon Tum",
    code: "62",
  },
  {
    name: "Đắk Nông",
    slug: "dak-nong",
    type: "tinh",
    name_with_type: "Tỉnh Đắk Nông",
    code: "67",
  },
  {
    name: "Sóc Trăng",
    slug: "soc-trang",
    type: "tinh",
    name_with_type: "Tỉnh Sóc Trăng",
    code: "94",
  },
  {
    name: "Bình Phước",
    slug: "binh-phuoc",
    type: "tinh",
    name_with_type: "Tỉnh Bình Phước",
    code: "70",
  },
  {
    name: "Hưng Yên",
    slug: "hung-yen",
    type: "tinh",
    name_with_type: "Tỉnh Hưng Yên",
    code: "33",
  },
  {
    name: "Thanh Hóa",
    slug: "thanh-hoa",
    type: "tinh",
    name_with_type: "Tỉnh Thanh Hóa",
    code: "38",
  },
  {
    name: "Quảng Trị",
    slug: "quang-tri",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Trị",
    code: "45",
  },
  {
    name: "Tuyên Quang",
    slug: "tuyen-quang",
    type: "tinh",
    name_with_type: "Tỉnh Tuyên Quang",
    code: "08",
  },
  {
    name: "Quảng Ngãi",
    slug: "quang-ngai",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Ngãi",
    code: "51",
  },
  {
    name: "Hà Nội",
    slug: "ha-noi",
    type: "thanh-pho",
    name_with_type: "Thành phố Hà Nội",
    code: "01",
  },
  {
    name: "Lào Cai",
    slug: "lao-cai",
    type: "tinh",
    name_with_type: "Tỉnh Lào Cai",
    code: "10",
  },
  {
    name: "Vĩnh Long",
    slug: "vinh-long",
    type: "tinh",
    name_with_type: "Tỉnh Vĩnh Long",
    code: "86",
  },
  {
    name: "Lâm Đồng",
    slug: "lam-dong",
    type: "tinh",
    name_with_type: "Tỉnh Lâm Đồng",
    code: "68",
  },
  {
    name: "Bình Định",
    slug: "binh-dinh",
    type: "tinh",
    name_with_type: "Tỉnh Bình Định",
    code: "52",
  },
  {
    name: "Nghệ An",
    slug: "nghe-an",
    type: "tinh",
    name_with_type: "Tỉnh Nghệ An",
    code: "40",
  },
  {
    name: "Kiên Giang",
    slug: "kien-giang",
    type: "tinh",
    name_with_type: "Tỉnh Kiên Giang",
    code: "91",
  },
  {
    name: "Hà Giang",
    slug: "ha-giang",
    type: "tinh",
    name_with_type: "Tỉnh Hà Giang",
    code: "02",
  },
  {
    name: "Phú Yên",
    slug: "phu-yen",
    type: "tinh",
    name_with_type: "Tỉnh Phú Yên",
    code: "54",
  },
  {
    name: "Lạng Sơn",
    slug: "lang-son",
    type: "tinh",
    name_with_type: "Tỉnh Lạng Sơn",
    code: "20",
  },
  {
    name: "Đà Nẵng",
    slug: "da-nang",
    type: "thanh-pho",
    name_with_type: "Thành phố Đà Nẵng",
    code: "48",
  },
  {
    name: "Sơn La",
    slug: "son-la",
    type: "tinh",
    name_with_type: "Tỉnh Sơn La",
    code: "14",
  },
  {
    name: "Tây Ninh",
    slug: "tay-ninh",
    type: "tinh",
    name_with_type: "Tỉnh Tây Ninh",
    code: "72",
  },
  {
    name: "Nam Định",
    slug: "nam-dinh",
    type: "tinh",
    name_with_type: "Tỉnh Nam Định",
    code: "36",
  },
  {
    name: "Lai Châu",
    slug: "lai-chau",
    type: "tinh",
    name_with_type: "Tỉnh Lai Châu",
    code: "12",
  },
  {
    name: "Bến Tre",
    slug: "ben-tre",
    type: "tinh",
    name_with_type: "Tỉnh Bến Tre",
    code: "83",
  },
  {
    name: "Khánh Hòa",
    slug: "khanh-hoa",
    type: "tinh",
    name_with_type: "Tỉnh Khánh Hòa",
    code: "56",
  },
  {
    name: "Bình Thuận",
    slug: "binh-thuan",
    type: "tinh",
    name_with_type: "Tỉnh Bình Thuận",
    code: "60",
  },
  {
    name: "Cao Bằng",
    slug: "cao-bang",
    type: "tinh",
    name_with_type: "Tỉnh Cao Bằng",
    code: "04",
  },
  {
    name: "Hải Phòng",
    slug: "hai-phong",
    type: "thanh-pho",
    name_with_type: "Thành phố Hải Phòng",
    code: "31",
  },
  {
    name: "Ninh Bình",
    slug: "ninh-binh",
    type: "tinh",
    name_with_type: "Tỉnh Ninh Bình",
    code: "37",
  },
  {
    name: "Yên Bái",
    slug: "yen-bai",
    type: "tinh",
    name_with_type: "Tỉnh Yên Bái",
    code: "15",
  },
  {
    name: "Gia Lai",
    slug: "gia-lai",
    type: "tinh",
    name_with_type: "Tỉnh Gia Lai",
    code: "64",
  },
  {
    name: "Hoà Bình",
    slug: "hoa-binh",
    type: "tinh",
    name_with_type: "Tỉnh Hoà Bình",
    code: "17",
  },
  {
    name: "Bà Rịa - Vũng Tàu",
    slug: "ba-ria-vung-tau",
    type: "tinh",
    name_with_type: "Tỉnh Bà Rịa - Vũng Tàu",
    code: "77",
  },
  {
    name: "Cà Mau",
    slug: "ca-mau",
    type: "tinh",
    name_with_type: "Tỉnh Cà Mau",
    code: "96",
  },
  {
    name: "Bình Dương",
    slug: "binh-duong",
    type: "tinh",
    name_with_type: "Tỉnh Bình Dương",
    code: "74",
  },
  {
    name: "Cần Thơ",
    slug: "can-tho",
    type: "thanh-pho",
    name_with_type: "Thành phố Cần Thơ",
    code: "92",
  },
  {
    name: "Thừa Thiên Huế",
    slug: "thua-thien-hue",
    type: "tinh",
    name_with_type: "Tỉnh Thừa Thiên Huế",
    code: "46",
  },
  {
    name: "Đồng Nai",
    slug: "dong-nai",
    type: "tinh",
    name_with_type: "Tỉnh Đồng Nai",
    code: "75",
  },
  {
    name: "Tiền Giang",
    slug: "tien-giang",
    type: "tinh",
    name_with_type: "Tỉnh Tiền Giang",
    code: "82",
  },
  {
    name: "Điện Biên",
    slug: "dien-bien",
    type: "tinh",
    name_with_type: "Tỉnh Điện Biên",
    code: "11",
  },
  {
    name: "Vĩnh Phúc",
    slug: "vinh-phuc",
    type: "tinh",
    name_with_type: "Tỉnh Vĩnh Phúc",
    code: "26",
  },
  {
    name: "Quảng Nam",
    slug: "quang-nam",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Nam",
    code: "49",
  },
  {
    name: "Đắk Lắk",
    slug: "dak-lak",
    type: "tinh",
    name_with_type: "Tỉnh Đắk Lắk",
    code: "66",
  },
  {
    name: "Thái Nguyên",
    slug: "thai-nguyen",
    type: "tinh",
    name_with_type: "Tỉnh Thái Nguyên",
    code: "19",
  },
  {
    name: "Hải Dương",
    slug: "hai-duong",
    type: "tinh",
    name_with_type: "Tỉnh Hải Dương",
    code: "30",
  },
  {
    name: "Bạc Liêu",
    slug: "bac-lieu",
    type: "tinh",
    name_with_type: "Tỉnh Bạc Liêu",
    code: "95",
  },
  {
    name: "Trà Vinh",
    slug: "tra-vinh",
    type: "tinh",
    name_with_type: "Tỉnh Trà Vinh",
    code: "84",
  },
  {
    name: "Thái Bình",
    slug: "thai-binh",
    type: "tinh",
    name_with_type: "Tỉnh Thái Bình",
    code: "34",
  },
  {
    name: "Hà Tĩnh",
    slug: "ha-tinh",
    type: "tinh",
    name_with_type: "Tỉnh Hà Tĩnh",
    code: "42",
  },
  {
    name: "Ninh Thuận",
    slug: "ninh-thuan",
    type: "tinh",
    name_with_type: "Tỉnh Ninh Thuận",
    code: "58",
  },
  {
    name: "Đồng Tháp",
    slug: "dong-thap",
    type: "tinh",
    name_with_type: "Tỉnh Đồng Tháp",
    code: "87",
  },
  {
    name: "Long An",
    slug: "long-an",
    type: "tinh",
    name_with_type: "Tỉnh Long An",
    code: "80",
  },
  {
    name: "Hậu Giang",
    slug: "hau-giang",
    type: "tinh",
    name_with_type: "Tỉnh Hậu Giang",
    code: "93",
  },
  {
    name: "Quảng Ninh",
    slug: "quang-ninh",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Ninh",
    code: "22",
  },
  {
    name: "Phú Thọ",
    slug: "phu-tho",
    type: "tinh",
    name_with_type: "Tỉnh Phú Thọ",
    code: "25",
  },
  {
    name: "Quảng Bình",
    slug: "quang-binh",
    type: "tinh",
    name_with_type: "Tỉnh Quảng Bình",
    code: "44",
  },
  {
    name: "Hồ Chí Minh",
    slug: "ho-chi-minh",
    type: "thanh-pho",
    name_with_type: "Thành phố Hồ Chí Minh",
    code: "79",
  },
  {
    name: "Hà Nam",
    slug: "ha-nam",
    type: "tinh",
    name_with_type: "Tỉnh Hà Nam",
    code: "35",
  },
  {
    name: "Bắc Ninh",
    slug: "bac-ninh",
    type: "tinh",
    name_with_type: "Tỉnh Bắc Ninh",
    code: "27",
  },
  {
    name: "Bắc Giang",
    slug: "bac-giang",
    type: "tinh",
    name_with_type: "Tỉnh Bắc Giang",
    code: "24",
  },
  {
    name: "Bắc Kạn",
    slug: "bac-kan",
    type: "tinh",
    name_with_type: "Tỉnh Bắc Kạn",
    code: "06",
  },
];

export { coutries, vietnameCities };
